ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; ALTER SYSTEM SET DB_16K_CACHE_SIZE=4M SCOPE=BOTH;

CREATE USER PROYECTO_MOVILES
  IDENTIFIED BY PROYECTO_MOVILES
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT RESOURCE TO PROYECTO_MOVILES;
GRANT CONNECT TO PROYECTO_MOVILES;
ALTER USER PROYECTO_MOVILES DEFAULT ROLE ALL;
  GRANT CREATE VIEW TO PROYECTO_MOVILES;
GRANT UNLIMITED TABLESPACE TO PROYECTO_MOVILES;
  GRANT CREATE ANY TABLE TO PROYECTO_MOVILES WITH ADMIN OPTION;
  GRANT CREATE SESSION TO PROYECTO_MOVILES;


ALTER SESSION SET CURRENT_SCHEMA = PROYECTO_MOVILES;

-- Tabla USUARIO
CREATE TABLE Usuario (
    id NUMBER PRIMARY KEY,
    nombre VARCHAR2(100),
    correo VARCHAR2(100),
    contrasena VARCHAR2(100)
);

-- Tabla CARRITO
CREATE TABLE Carrito (
    id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    fechaCreacion DATE,
    idUsuario NUMBER UNIQUE,
    FOREIGN KEY (idUsuario) REFERENCES Usuario(id)
);

-- Tabla PRODUCTO
CREATE TABLE Producto (
    id VARCHAR2(15) PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(255),
    precio FLOAT,
    stock INT
);

-- Tabla CARRITOITEM
CREATE TABLE CarritoItem (
    idCarrito NUMBER,
    idProducto VARCHAR2(15),
    cantidad INT,
    subtotal FLOAT,
    PRIMARY KEY (idCarrito, idProducto),
    FOREIGN KEY (idCarrito) REFERENCES Carrito(id),
    FOREIGN KEY (idProducto) REFERENCES Producto(id)
);

-- Tabla ORDEN
CREATE TABLE Orden (
    id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    fecha DATE,
    total FLOAT,
    estado VARCHAR2(50),
    idUsuario NUMBER,
    FOREIGN KEY (idUsuario) REFERENCES Usuario(id)
);

-- Tabla DIRECCIONENVIO
CREATE TABLE DireccionEnvio (
    idOrden NUMBER PRIMARY KEY,
    calle VARCHAR2(100),
    ciudad VARCHAR2(100),
    pais VARCHAR2(100),
    codigoPostal VARCHAR2(20),
    FOREIGN KEY (idOrden) REFERENCES Orden(id)
);

-- Tabla PAGO
CREATE TABLE Pago (
    id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    metodo VARCHAR2(50),
    monto FLOAT,
    idOrden NUMBER UNIQUE,
    FOREIGN KEY (idOrden) REFERENCES Orden(id)
);